### ISSUE TITLE
Error during installation: `TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /.../generateGraphTestsData.ts`

### ISSUE THREAD

**Issue by Kasahs** [henriqueinonhe/promises-training#34]
Tried install using `npm create promises-training@latest`

got the following error:
```
Initializing graph exercises tests data...

> create-promises-training@1.0.1 graph:generateTests
> ts-node ./scripts/generateGraphTestsData.ts

TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /Users/sxxxxxa/Code/promise-trainer/scripts/generateGraphTestsData.ts
    at new NodeError (node:internal/errors:405:5)
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:99:9)
    at defaultGetFormat (node:internal/modules/esm/get_format:142:36)
    at defaultLoad (node:internal/modules/esm/load:91:20)
    at nextLoad (node:internal/modules/esm/hooks:733:28)
    at load (/Users/shxxxxa/Code/promise-trainer/node_modules/ts-node/dist/child/child-loader.js:19:122)
    at nextLoad (node:internal/modules/esm/hooks:733:28)
    at Hooks.load (node:internal/modules/esm/hooks:377:26)
    at MessagePort.handleMessage (node:internal/modules/esm/worker:168:24)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:778:20) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}

Error initializing graph exercises tests data
Error: Command failed: npm run graph:generateTests
    at checkExecSyncError (node:child_process:887:11)
    at execSync (node:child_process:959:15)
    at run (/Users/shxxxxa/.npm/_npx/117e15c697a42bb1/node_modules/create-promises-training/bin.cjs:19:3)
    at initializeGraphTestsData (/Users/shxxxxa/.npm/_npx/117e15c697a42bb1/node_modules/create-promises-training/bin.cjs:155:5)
    at setup (/Users/shxxxxa/.npm/_npx/117e15c697a42bb1/node_modules/create-promises-training/bin.cjs:45:9)
    at async main (/Users/shxxxxxa/.npm/_npx/117e15c697a42bb1/node_modules/create-promises-training/bin.cjs:32:3) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 30204,
  stdout: null,
  stderr: null
}
```

**Comment by di5ko** [comment]
+1

MacOS

```
~/git/promises-training [master] $ node -v
v20.10.0
~/git/promises-training [master] $ npm -v
10.2.4
```

**Comment by henriqueinonhe** [comment]
Thanks for reporting, I'm investigating, will give feedback soon

**Comment by henriqueinonhe** [comment]
The issue is being caused by this: https://github.com/TypeStrong/ts-node/issues/1997

I'm working on a fix

**Comment by henriqueinonhe** [comment]
Fixed in https://github.com/henriqueinonhe/promises-training/releases/tag/v2.0.0
