### ISSUE TITLE
Error initializing graph exercises tests data

### ISSUE THREAD

**Issue by Ulisseus** [henriqueinonhe/promises-training#35]
Fresh install. Windows 10, node v18.15.0. For some reason script tried to navigate to `'D:\D:\work\promises\.data\graph` which is obviously an incorrect path. 

```
Initializing graph exercises tests data...

> create-promises-training@1.0.1 graph:generateTests
> ts-node ./scripts/generateGraphTestsData.ts

[Error: ENOENT: no such file or directory, mkdir 'D:\D:\work\promises\.data\graph'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'mkdir',
  path: 'D:\\D:\\work\\promises\\.data\\graph'
}

Error initializing graph exercises tests data
Error: Command failed: npm run graph:generateTests
    at checkExecSyncError (node:child_process:885:11)
    at execSync (node:child_process:957:15)
    at run (C:\Users\Uliss\AppData\Local\npm-cache\_npx\117e15c697a42bb1\node_modules\create-promises-training\bin.cjs:19:3)
    at initializeGraphTestsData (C:\Users\Uliss\AppData\Local\npm-cache\_npx\117e15c697a42bb1\node_modules\create-promises-training\bin.cjs:155:5)
    at setup (C:\Users\Uliss\AppData\Local\npm-cache\_npx\117e15c697a42bb1\node_modules\create-promises-training\bin.cjs:45:9)
    at async main (C:\Users\Uliss\AppData\Local\npm-cache\_npx\117e15c697a42bb1\node_modules\create-promises-training\bin.cjs:32:3) {
  status: 1,
  output: [ null, null, null ],
  pid: 12484,
  stderr: null
}
npm notice
npm notice New major version of npm available! 9.5.0 -> 10.2.4
npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.2.4
npm notice Run npm install -g npm@10.2.4 to update!
npm notice
npm ERR! code 1
npm ERR! path D:\work\promises
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c create-promises-training

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Uliss\AppData\Local\npm-cache\_logs\2023-11-24T10_54_16_816Z-debug-0.log
```
[2023-11-24T10_54_16_816Z-debug-0.log](https://github.com/henriqueinonhe/promises-training/files/13458294/2023-11-24T10_54_16_816Z-debug-0.log)

**Comment by henriqueinonhe** [comment]
Thanks for reporting!

I found the issue, will be shipping a fix soon!

**Comment by henriqueinonhe** [comment]
Fixed in https://github.com/henriqueinonhe/promises-training/releases/tag/v2.0.0
